export default [
	{ desc: "🌶️ Jalapeños for the steamy social salsa sesh", amount: -9.57 },
	{ desc: "👩‍💻 Payment for club coding lessons (solid gold)", amount: -127.63 },
	{ desc: "🍺 Reimbursement for team-building pub crawl", amount: -88.9 },
	{ desc: "😨 Monthly payment to the local protection racket", monthly: true, amount: -2_500.0 },
	{ desc: "🚀 Rocket fuel for Lucas' commute", amount: -50.0 },
	{ desc: "💰 Donation from t̶͖̯́̒̇͝h̸͇̥̘̖̞̋͛̕ę̷̧̯̓̄͜ ̵̧̡̀̎͋̚v̸̰̰̝͈̟̂̇̏̓ͅo̶͓͈͑̑̄̍i̸͉̺͕̥̓̍d̵̟̮̼̠̺̿͌́", amount: 50_000.0 },
	{ desc: "🎵 Payment for a DJ for the club disco (groovy)", amount: -430.0 },
	{ desc: "🤫 Hush money", amount: -1000.0 },
	{ desc: "🦄 Purchase of a cute unicorn for team morale", amount: -57.0 },
	{ desc: "🍌 Bananas (Fairtrade)", amount: -1.8 },
	{ desc: "💸 Withdrawal for emergency pizza run", amount: -62.99 },
	{ desc: "🍔 Withdrawal for a not-so-emergency burger run", amount: -47.06 },
	{ desc: "🧑‍🚀 Astronaut suit for Lucas to get home when it's cold", amount: -943.99 },
	{ desc: "💰 Donation from the man in the walls", amount: 1_200.0, monthly: true },
	{ desc: "🫘 Chilli con carne (home cooked, just how you like it)", amount: -8.28 },
	{ desc: "🦖 Purchase of a teeny tiny T-Rex", amount: -3.35 },
	{ desc: "🧪 Purchase of lab rats for the club's genetics project", amount: -120.0 },
	{ desc: "🐣 An incubator to help hatch big ideas", amount: -1.59 },
	{ desc: "📈 Financial advisor to teach us better spending tips", amount: -900.0 },
	{ desc: "🐛 Office wormery", amount: -47.53 },
	{ desc: "📹 Webcams for the team x4", amount: -199.96 },
	{ desc: "🪨 Hackathon rock tumbler", amount: -19.99 },
	{ desc: "🌸 Payment for a floral arrangement", monthly: true, amount: -15.5 },
	{ desc: "🧼 Purchase of eco-friendly soap for the club bathrooms", monthly: true, amount: -7.49 },
	{ desc: "💰 Donation from Dave from next door", monthly: true, amount: 250.0 },
	{ desc: "💰 Donation from Old Greg down hill", amount: 500.0 },
	{ desc: "💳 Transfer received for the annual web hosting fee", amount: 500.0 },
	{ desc: "🎟️ Proceeds from ticket sales for the charity concert", amount: 2_500.0 },
	{ desc: "🏆 Prize money for the first place in the local hackathon", amount: 1_000.0 },
	{ desc: "🛍️ Refund from overcharged supplies", amount: 110.0 },
	{ desc: "📲 Mobile app revenue for the month", amount: 1_200.0 },
	{ desc: "🤝 Sponsorship received for annual tech conference", amount: 5_000.0 },
	{ desc: "🚀 Dividend from lunar real estate investment", amount: 7_528.46 },
	{ desc: "💡 Perpetual motion machine patent royalties", amount: 50_000.0 },
	{ desc: "💼 Shady spy briefcase swap profit", amount: 800.0 }
];
